{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": true
   },
   "source": [
    "\n",
    "## Exceptions VII\n",
    "### Creating Our Own Exception Classes\n",
    "__In this notebook, we  study how we can create and use our own exception classes.__\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__All user defined exception classes are derived from the base class called `Exception`. To create your own user defined class, you need have nothing but the class heading.__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    " User defined exception class\n",
    "'''\n",
    "class DivisionByTwoError(Exception):\n",
    "    pass #This statement is only required for syntactic purposes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    " User defined exception class\n",
    "'''\n",
    "class DivisionByThreeError(Exception):\n",
    "    '''\n",
    "    The string returned by the redefined __str__ method, will be printed when we print the exception object.\n",
    "    '''\n",
    "    def __str__(self):\n",
    "        return 'Numbers divisible by three are not acceptable'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__In this example, we raise an DivisionByThree exception if the user enters a numerator value that is divisible by three. We raise a `DivisionByTwo` exception if the numerator value is divisible by two. A `ZeroDivisionError` exception will be automatically raised, if the user enters zero for the denominator.__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the numerator:15\n",
      "Enter the denominator: 12\n",
      "Numerator cannot be divisible by Three!!\n",
      " Numbers divisible by three are not acceptable\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "  Raising user defined and automatic exceptions\n",
    "'''\n",
    "try:\n",
    "    n1 = int(input('Enter the numerator:'))\n",
    "    n2 = int(input('Enter the denominator: '))\n",
    "    if n1 % 3 == 0:\n",
    "        raise DivisionByThreeError\n",
    "    if n1 % 2 == 0:\n",
    "        raise DivisionByTwoError\n",
    "    quo = n1/n2\n",
    "    print('The quotient when dividing', n1, 'by', n2, 'is:', quo)\n",
    "except ZeroDivisionError:\n",
    "    print('Division by zero is not allowed!!')\n",
    "except DivisionByThreeError as e:\n",
    "    # Note that the string variable of the exception object is also printed\n",
    "    print('Numerator cannot be divisible by Three!!\\n', e)\n",
    "except DivisionByTwoError:\n",
    "    print('Numerator cannot be divisible by Two!!\\n')\n",
    "except Exception:\n",
    "    print('Error in input!')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__This example is similar to the one above, except that it now includes an else block which contains within it another `try/except` block__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the numerator:7\n",
      "Enter the denominator: 0\n",
      "Division by zero is not allowed!!\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "  Nested try/except blocks\n",
    "  First try/except block: guards against errors generated by first number (DivisionByTwo, DivisionByThree, Other)\n",
    "  Second try/except block: guards against errors generated by second number (ZeroDivisionError, Other)\n",
    "'''\n",
    "try:\n",
    "    n1 = int(input('Enter the numerator:'))\n",
    "    if n1 % 3 == 0:\n",
    "        raise DivisionByThreeError\n",
    "    if n1 % 2 == 0:\n",
    "        raise DivisionByTwoError\n",
    "except DivisionByTwoError:\n",
    "    print('Numerator cannot be divisible by Two!!\\n')\n",
    "except DivisionByThreeError as e:\n",
    "    print('Numerator cannot be divisible by Three!!\\n',e)\n",
    "except Exception:\n",
    "    print('Error!')\n",
    "else:\n",
    "    try:\n",
    "        n2 = int(input('Enter the denominator: '))\n",
    "        quo = n1/n2\n",
    "        print('The quotient when dividing', n1, 'by', n2, 'is:', quo)\n",
    "    except ZeroDivisionError:\n",
    "        print('Division by zero is not allowed!!')\n",
    "    except Exception:\n",
    "        print('Error!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
